# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_geod_wrappers", use_symbols = TRUE, package_name = "geod")

#' @docType package
#' @usage NULL
#' @useDynLib geod, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' @export
add <- function(x, y) .Call(wrap__add, x, y)

#' @export
utm <- function(xx, yy) .Call(wrap__utm, xx, yy)

#' @export
rumination_000 <- function() .Call(wrap__rumination_000)


# nolint end
